Agenda/config/routes.rb
Rails.application.routes.draw do
  resources :tests
  resources :pessoas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Agenda/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Agenda/app/models/pessoa.rb
class Pessoa < ApplicationRecord
end

Agenda/app/models/test.rb
class Test < ApplicationRecord
end

Agenda/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Agenda/app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]

  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: 'Pessoa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_params
      params.require(:pessoa).permit(:nome, :fantasia, :comercial, :celular, :residencial, :email, :endereco, :cidade, :pais, :estado, :cep, :observacao)
    end
end

Agenda/app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]

  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @test = Test.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @test }
      else
        format.html { render :edit }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test.destroy
    respond_to do |format|
      format.html { redirect_to tests_url, notice: 'Test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_params
      params.require(:test).permit(:nome, :endereco)
    end
end

Agenda/app/helpers/application_helper.rb
module ApplicationHelper
end

Agenda/app/helpers/pessoas_helper.rb
module PessoasHelper
end

Agenda/app/helpers/tests_helper.rb
module TestsHelper
end

Agenda/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>South Wind Systems</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "South Wind Systems", pessoas_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li> <%= link_to('Agenda', pessoas_path) %></li>          
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

Agenda/app/views/pessoas/_form.html.erb
<%= form_for(@pessoa, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @pessoa.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h4>

      <ul>
      <% @pessoa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control"  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :fantasia, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :fantasia, class: "form-control" %>
    </div>
  </div> 

  <div class="form-group">
    <%= f.label :cep, class: "col-sm-2 control-label" %>
    <div class="col-sm-2">
      <%= f.text_field :cep, class: "form-control" %>
    </div>


    <%= f.label :endereco, class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :endereco, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :cidade, class: "col-sm-2 control-label" %>
    <div class="col-sm-2">
      <%= f.text_field :cidade, class: "form-control" %>
    </div>

    <%= f.label :pais, class: "col-sm-2 control-label" %>
    <div class="col-sm-3">
      <%= f.text_field :pais, class: "form-control" %>
    </div>

    <%= f.label :estado, class: "col-sm-2 control-label" %>
    <div class="col-sm-1">
      <%= f.text_field :estado,  class: "form-control"  %>
    </div>
  </div>


   <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
   </div>
   
   <div class="form-group">
    <%= f.label :comercial, class: "col-sm-2 control-label" %>
    <div class="col-sm-2">
      <%= f.text_field :comercial, class: "form-control"  %>
    </div>

    <%= f.label :celular, class: "col-sm-2 control-label" %>
    <div class="col-sm-2">
      <%= f.text_field :celular, class: "form-control" %>
    </div>

    <%= f.label :residencial, class: "col-sm-2 control-label" %>
    <div class="col-sm-2">
      <%= f.text_field :residencial, class: "form-control"  %>
    </div>
  </div>     

  <div class="form-group">
    <%= f.label :observacao, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :observacao ,:rows => 10, class: "form-control"   %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

Agenda/app/views/pessoas/edit.html.erb
<div class="page-header">
  <%= link_to pessoas_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @pessoa, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing pessoa</h1>
</div>

<%= render 'form' %>

Agenda/app/views/pessoas/index.html.erb
<div class="page-header">
  <%= link_to new_pessoa_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Pessoa
  <% end %>
  <h1>Listing pessoas</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Nome</th>
            <th>Fantasia</th>
            <th>Comercial</th>
            <th>Celular</th>
            <th>Residencial</th>
            <th>Email</th>

            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @pessoas) do |pessoa| %>
            <td><%= pessoa.nome %></td>
            <td><%= pessoa.fantasia %></td>
            <td><%= pessoa.comercial %></td>
            <td><%= pessoa.celular %></td>
            <td><%= pessoa.residencial %></td>
            <td><%= pessoa.email %></td>

            <td><%= link_to 'Show', pessoa %></td>
        <td><%= link_to 'Edit', edit_pessoa_path(pessoa) %></td>
        <td><%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

Agenda/app/views/pessoas/new.html.erb
<div class="page-header">
  <%= link_to pessoas_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New pessoa</h1>
</div>

<%= render 'form' %>

Agenda/app/views/pessoas/show.html.erb
<div class="page-header">
  <%= link_to pessoas_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_pessoa_path(@pessoa), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show pessoa</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @pessoa.nome %></dd>

  <dt>Fantasia:</dt>
  <dd><%= @pessoa.fantasia %></dd>

  <dt>Comercial:</dt>
  <dd><%= @pessoa.comercial %></dd>

  <dt>Celular:</dt>
  <dd><%= @pessoa.celular %></dd>

  <dt>Residencial:</dt>
  <dd><%= @pessoa.residencial %></dd>

  <dt>Email:</dt>
  <dd><%= @pessoa.email %></dd>

  <dt>Endereco:</dt>
  <dd><%= @pessoa.endereco %></dd>

  <dt>Cidade:</dt>
  <dd><%= @pessoa.cidade %></dd>

  <dt>Pais:</dt>
  <dd><%= @pessoa.pais %></dd>

  <dt>Estado:</dt>
  <dd><%= @pessoa.estado %></dd>

  <dt>Cep:</dt>
  <dd><%= @pessoa.cep %></dd>

  <dt>Observacao:</dt>
  <dd><%= @pessoa.observacao %></dd>

</dl>